# Etapa 1: Construcción de la aplicación
FROM golang:1.19 AS builder

WORKDIR /app

# Copia el archivo go.mod y go.sum
COPY go.mod go.sum ./

# Copia el código fuente
COPY . .

# Compila la aplicación como un binario estático
RUN CGO_ENABLED=0 GOOS=linux go build -o backend .

# Etapa 2: Imagen final
FROM alpine:3.17

WORKDIR /app

# Copia el binario compilado desde la etapa de construcción
COPY --from=builder /app/backend .

# Verifica que el binario se haya copiado correctamente
RUN ls -l /app/backend

EXPOSE 8080

CMD ["./backend"]
