# Usa una imagen oficial de Python como base
FROM python:3.11-alpine

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia el archivo de requisitos y las dependencias en el contenedor
COPY requirements.txt .

# Instala las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Copia el código fuente en el contenedor
COPY . .

# Expone el puerto en el que la aplicación va a correr
EXPOSE 5001

# Define el comando que se ejecutará cuando el contenedor se inicie
CMD ["python3", "main.py"]
